package infsolution.com.br.fidelize.enums;

/**
 * Created by Cicero on 05/06/2016.
 */
public enum Cargo {
VEREADOR, VISE_PREFEITO, PREFEITO, DEPUTADO_ESTADUAL,DEPUTADO_FEDERAL, DEPUTADOR_DISTRITAL, SENADOR, VISE_GOVERNADOR, GOVERNADOR, VISE_PRESIDENTE, PRESIDENTE;
}
